### ISSUE TITLE
Update to latest Material Icons?

### ISSUE THREAD

**Issue by joelkesler** [Christilut/material-icons-aliases#11]
Hi! 

It looks like Google has taken your ideas to heart and added a similar fuzzy search to the new https://fonts.google.com/icons site.

But that also means it is much easier to pull in their changes and aliases into your project! They have the json with icon names and tags here:
https://fonts.google.com/metadata/icons

I still kind of like your project better, as it automatically sticks to the "filled" icon style and allows one to copy and paste the icon straight from the page

**Comment by Christilut** [comment]
I'm actually using https://materialdesignicons.com/ nowadays. It also has community icons and with a fuzzy search, although the website is dreadfully slow.

**Comment by joelkesler** [comment]
Do you have time to your README and site to mentioned that the material-icon-aliases project has been discontinued, while pointing to the new Google Fonts icon search?

The Google Fonts site now allows you to link to a specific icon font and font style too!
Here is a link for the 'filled' style Material Icons font:
https://fonts.google.com/icons?icon.style=Filled&icon.set=Material+Icons

**Comment by Christilut** [comment]
Sure thing! Thanks for letting me know about that
