### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Rainbowlemon** [Christilut/material-icons-aliases#4]
Hey! I'm a regular user of your site, and have recently noticed your site is down. Is this a temporary thing?

**Comment by Christilut** [comment]
Hey,

I figured no one was using it anymore but I guess I was wrong. I've uploaded it to [Github Pages](https://christilut.github.io/material-icons-aliases), it'll stay there forever 👍

**Comment by Rainbowlemon** [comment]
Ah brilliant, thank you!
